version = 1

test_patterns = ["app/tests/test_*.py"]

exclude_patterns = [
    "bin/**",
    "docs/**",
    "fonts/**",
    "templates/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
